//
//  Pantry.swift
//  FIT3178-Assignment
//
//  Created by Ojaswi Pandey on 22/9/2025.
//
//  Data models for pantry items
//  FoodCategory enum defines all food types
//  Pantry class stores information about each food item in the pantry

import UIKit

// FoodCategory = An enumeration of all food types
// Each food item belongs to one of these categories
enum FoodCategory: Int, CaseIterable, Codable {
    
    case beverages = 0
    case dairy = 1
    case fruits = 2
    case vegetables = 3
    case grains = 4
    case proteins = 5
    case snacks = 6
    case condiments = 7
    
    // A readable name for each category
    // Used when showing categories to the user
    var displayName: String {
        switch self {
        case .beverages:
            return "Beverages"
        case .dairy:
            return "Dairy"
        case .fruits:
            return "Fruits"
        case .vegetables:
            return "Vegetables"
        case .grains:
            return "Grains"
        case .proteins:
            return "Proteins"
        case .snacks:
            return "Snacks"
        case .condiments:
            return "Condiments"
        }
    }
}

// Stores all information about what the user has
class Pantry: NSObject, Codable {
    // id = The unique ID for this item in the database
    // Generated by Firebase when the item is created
    var id: String?
    
    // name = The name of the food item
    var name: String?
    
    // quantity = How many of this item the user has
    var quantity: Int?
    
    // category = What type of food is this?
    var category: FoodCategory?
    
    // Obtained from barcode scanner or manual entry
    var calories: Int?
    var fat: Double?
    var carbs: Double?
    var protein: Double?
    var nutritionGrade: String?
    
    // date = The expiry date of this item
    // When this date passes, the item is considered expired
    var date: Date?
    var barcode: String?
    
    // userId = The user ID of who owns this item
    // Tracks which user's pantry this belongs to
    var userId: String?
    
    // Create a new Pantry item with all the information
    init(name: String?, quantity: Int?, calories: Int?, date: Date?, category: FoodCategory?, barcode: String? = nil, fat: Double? = nil, carbs: Double? = nil, protein: Double? = nil, nutritionGrade: String? = nil) {
        // Save the item name
        self.name = name
        // Save how many units
        self.quantity = quantity
        // Save calories
        self.calories = calories
        // Save expiry date
        self.date = date
        // Save category
        self.category = category
        // Save barcode
        self.barcode = barcode
        // Save fat content
        self.fat = fat
        // Save carbs content
        self.carbs = carbs
        // Save protein content
        self.protein = protein
        // Save nutrition grade
        self.nutritionGrade = nutritionGrade
        // Initialize parent class
        super.init()
    }
    
    // Convenience initializer - creates an empty pantry item
    convenience override init() {
        // Call main init with all nil values
        self.init(name: nil, quantity: nil, calories: nil, date: nil, category: nil, barcode: nil, fat: nil, carbs: nil, protein: nil, nutritionGrade: nil)
    }
}
