//
//  ShoppingItem.swift
//  FIT3178-Assignment
//
//  Created by Ojaswi Pandey on 23/9/2025.
//
//  Stores information about an item in the shopping list
//  Each shopping item has a name, quantity, category, and other details
//  Can be converted to a pantry item when user wants to add it to pantry

import UIKit

class ShoppingItem: NSObject {
    
    // id = The unique ID for this item in the database
    // Generated by Firebase when the item is created
    var id: String?
    
    // name = The name of the item (e.g., "Milk", "Eggs", "Bread")
    var name: String?
    
    // quantity = How many of this item to buy
    var quantity: Int?
    
    // isPurchased = Has user checked off this item as purchased?
    // Default is false (not purchased yet)
    var isPurchased: Bool = false
    
    // category = What type of food is this?
    // Examples: beverages, dairy, fruits, vegetables, etc.
    var category: FoodCategory?
    
    // calories = How many calories per 100g
    // Used if barcode scanner found nutrition info
    var calories: Int?
    
    // userId = The user ID of who owns this item
    // Tracks which user's shopping list this belongs to
    var userId: String?
    
    // Create a new shopping item with name, quantity, category, and calories
    init(name: String?, quantity: Int?, category: FoodCategory? = nil, calories: Int? = nil) {
        // Save the item name
        self.name = name
        // Save the quantity
        self.quantity = quantity
        // Save the category
        self.category = category
        // Save the calories
        self.calories = calories
        // Initialize the parent class
        super.init()
    }
    
    // Convenience initializer - creates an empty shopping item
    convenience override init() {
        // Call the main init with all nil values
        self.init(name: nil, quantity: nil, category: nil, calories: nil)
    }
    
    // Convert this shopping item to a pantry item
    // Used when user wants to add shopping item to their pantry
    func toPantryItem() -> Pantry {
        // Set expiry date to 7 days from today
        // 86400 = number of seconds in 1 day
        let expiryDate = Date().addingTimeInterval(86400 * 7)
        
        // Create and return a new Pantry item with the same data
        return Pantry(
            name: self.name,
            quantity: self.quantity,
            calories: self.calories,
            date: expiryDate,
            category: self.category ?? .beverages
        )
    }
}
